### ISSUE TITLE
Non-breaking component deprecations break clients

### ISSUE THREAD

**Issue by jpmarcotte** [neighborhoods/Prefab#83]
I think this might have to do with the declaration of `error_reporting(E_ALL)` and `set_error_handler` in `vendor/bin/prefab`, but Symfony upgraded from 4.1.8 to 4.2.0 and deprecated a class. This caused prefab to completely break for anyone using it.

@pmucha-55places has created a fix for this specific issue, but if Symfony deprecates something else in 4.3.0 (or any future minor version), it could happen again.

example:
```
root@c254c3c47157:/var/www/html/listing_service.neighborhoods.com# vendor/bin/prefab

Fatal error: Uncaught ErrorException: The "Symfony\Component\DependencyInjection\Compiler\RepeatedPass" class is deprecated since Symfony 4.2. in /var/www/html/listing_service.neighborhoods.com/vendor/symfony/dependency-injection/Compiler/RepeatedPass.php on line 14

ErrorException: The "Symfony\Component\DependencyInjection\Compiler\RepeatedPass" class is deprecated since Symfony 4.2. in /var/www/html/listing_service.neighborhoods.com/vendor/symfony/dependency-injection/Compiler/RepeatedPass.php on line 14

Call Stack:
    0.0104     400304   1. {main}() /var/www/html/listing_service.neighborhoods.com/vendor/neighborhoods/prefab/bin/prefab:0
    0.2095    1597768   2. Neighborhoods\Prefab\Prefab->generate() /var/www/html/listing_service.neighborhoods.com/vendor/neighborhoods/prefab/bin/prefab:22
    0.2095    1597768   3. Neighborhoods\Prefab\Protean\Container\Builder->build() /var/www/html/listing_service.neighborhoods.com/vendor/neighborhoods/prefab/src/Prefab.php:18
    0.2095    1597768   4. Neighborhoods\Prefab\Protean\Container\Builder->getContainer() /var/www/html/listing_service.neighborhoods.com/vendor/neighborhoods/prefab/src/Protean/Container/Builder.php:19
    0.2095    1597768   5. Neighborhoods\Prefab\Protean\Container\Builder->getSymfonyContainerBuilder() /var/www/html/listing_service.neighborhoods.com/vendor/neighborhoods/prefab/src/Protean/Container/Builder.php:27
   12.3865    3175368   6. Neighborhoods\Prefab\Symfony\Component\DependencyInjection\ContainerBuilder\Facade->build() /var/www/html/listing_service.neighborhoods.com/vendor/neighborhoods/prefab/src/Protean/Container/Builder.php:44
  407.6850    3353080   7. spl_autoload_call(???) /var/www/html/listing_service.neighborhoods.com/vendor/neighborhoods/prefab/fab/Symfony/Component/DependencyInjection/ContainerBuilder/Facade.php:94
  407.6850    3353176   8. Composer\Autoload\ClassLoader->loadClass(???) /var/www/html/listing_service.neighborhoods.com/vendor/neighborhoods/prefab/fab/Symfony/Component/DependencyInjection/ContainerBuilder/Facade.php:94
  407.6917    3353336   9. Composer\Autoload\includeFile(???) /var/www/html/listing_service.neighborhoods.com/vendor/composer/ClassLoader.php:322
  407.7004    3360016  10. include('/var/www/html/listing_service.neighborhoods.com/vendor/symfony/dependency-injection/Compiler/RepeatedPass.php') /var/www/html/listing_service.neighborhoods.com/vendor/composer/ClassLoader.php:444
  407.7005    3360336  11. trigger_error(???, ???) /var/www/html/listing_service.neighborhoods.com/vendor/symfony/dependency-injection/Compiler/RepeatedPass.php:14
  407.7005    3361448  12. {closure:/var/www/html/listing_service.neighborhoods.com/vendor/neighborhoods/prefab/bin/prefab:5-13}(???, ???, ???, ???, ???) /var/www/html/listing_service.neighborhoods.com/vendor/symfony/dependency-injection/Compiler/RepeatedPass.php:14
```

**Comment by nico-spada-virtasant** [comment]
It looks like this issue was solved in a previous version. At the moment we are using "symfony/dependency-injection": "^4.4". Feel free to re-open this issue again if you found any issue.

**Comment by jpmarcotte** [comment]
This issue wasn't about a specific deprecation warning (the description mentions that it was resolved separately), so much as any future deprecation warnings that will cause Prefab to break. (Prefab is not set up to adequately handle deprecation notices and other warnings that wouldn't otherwise break the code.) Since it's not currently an issue, I don't think this is necessarily high priority (those can be new issues as they come up), but I also don't think that this specific issue is resolved either.

Something along the lines of setting an error handler that did not throw an exception specifically for things like deprecation warnings is how I imagine this would be solved. (See the 2nd parameter under https://www.php.net/manual/en/function.set-error-handler.php). 

N.B. This all assumes that Prefab wants to follow general PHP practices of respecting that warnings / deprecations may be thrown by dependent code that is otherwise still functional. If Prefab specifically wants to tell all clients that deprecated code should never be executed in its stack, and that upgrading a dependency of prefab to a state that includes a deprecation (even if Prefab doesn't itself require the update*) should be considered an incompatibility, then this issue can be re-closed. This is a design / goals decision that has its own merits, but is not necessarily something that everyone agrees with, and an Open-Source project should consider that explicitly.

\* If it's helpful, I can lay out a scenario of how this can happen.

**Comment by nico-spada-virtasant** [comment]
Great point, we will add this on this [ticket](https://55places.atlassian.net/browse/PREF-283). Thanks a lot for the explanation and also let us know if the ticket is correct.

**Comment by jpmarcotte** [comment]
Yeah, looks like it. I was really hoping PHP supported registering separate error handlers for different levels, but it doesn't appear to be the case, so the conditional is probably the way to go. Also left a comment on the ticket about potential levels to consider. (Not that you have to include all of them, or that there might not be others worth considering, they just jumped out at me as the primary ones that might get thrown by other packages which Prefab relies on that wouldn't necessarily break execution)

**Comment by nico-spada-virtasant** [comment]
Issue address in release [v8.3.0](https://github.com/neighborhoods/Prefab/releases/tag/8.3.0). Thanks!
